#!/bin/sh

set nonomatch

(cd tests && ./clean)
rm -rf .mypy_cache

# the rest is common to all python directories
rm -f *.pyc *.pyo */*.pyc */*.pyo .test*.sum expected result install.out
rm -rf build *.egg-info dist __pycache__ */__pycache__ .coverage
rm -rf tests/home/.python-eggs .eggs tests/.coverage htmlcov tests/htmlcov
rm -rf .cache tests/.cache tests/home/.cache .tox .hypothesis .pytest_cache */.pytest_cache
