#!/usr/bin/env bash
# Set pip variable to select which version of python to use.
# Use pip2 or pip3.
pip=pip3
#editable='--editable'
editable=''

# clean out the existing installed versions
rm -rf ~/.local/lib/python*/site-packages/emborg*
rm -f ~/.local/bin/emborg*

# Remove build directories from a previous install to assure a clean install.
rm -rf build dist emborg.egg-info install.out

# Install emborg
$pip --quiet install --upgrade --user $editable .

# Remove build directories, because I like a clean directory.
# I cannot get this conditional to work.
#if [[ "x$editiable" == "x" ]]; then
#    echo "cleaning"
#    ./clean  # does not work with --editable
#fi
