#!/bin/sh

if [ -d EMBORG/home ] || [ -d EMBORG/configs.symlink ]; then
    fusermount -u EMBORG
fi

rm -f configs.symlink
rm -rf configs .config .local repositories home __pycache__ EMBORG
rm -rf .cache .hypothesis .test.sum .coverage .test.emborg.sum
